language: rust
rust:
  - nightly
  - beta
  - stable
sudo: false
cache: cargo

matrix:
  allow_failures:
    - rust:
        - stable
        - beta
  include:
    - name: cargo test
      os: linux

    - name: cargo test
      os: osx

    #- name: cargo test
    #  os: windows

    - name: cargo test (with minimal versions)
      os: linux
      script:
        - cargo update -Zminimal-versions
        - cargo test --all-features

    # Reminder: when updating this update the minimum required version in README.md
    - name: cargo test (minimum required version)
      rust: nightly-2019-02-15

    - name: cargo clippy
      rust: nightly
      script:
        - if rustup component add clippy-preview;
          then
            cargo clippy -- -Dwarnings -Drust-2018-idioms;
          else
            echo 'Skipping clippy';
          fi

    - name: cargo bench
      rust: nightly
      script:
        - cargo bench

    - name: cargo build --no-default-features
      rust: nightly
      script:
        - cargo build --no-default-features

    - name: cargo build (default features)
      rust: nightly
      script:
        - cargo build

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

script:
  - cargo test --all-features
  - cargo test --all-features --release

after_success:
  - travis-cargo --only nightly doc-upload

env:
  global:
    secure: yfndRzuByFmJTGJE06Zv+FqJoarjmctdCMgL2OgQuIg+qAdOIOgcBg4YYtL6bNatAyhfEzdyIAJcHW2cfURXT0y/WEnssBCjGWKvt/46F6RRHpMVXSt2nRJuMEVhYQy6IO+N6/oh35kSjpYXkN9o31lbQ2GI+bODXdA1swMuBTAAiQuDVLM9tEmYsoa4LLdkworTy1KPJ80zND+PXEQS4hli0RF4r+IHA8OZMCNn7XqPwo+/IbJfklQq76r0aYEBV+wsYRDjtU+nNc4vx+3SOPHKP+xRKb6QnW7bnww7WHw1NiK+Lied8f6cbhL30NWnEBOayk9VV53RgY8XTHpH1SfvFyRF/APy8wu/2fPOC0Uv3KThstv5yz6At2rlsoDFGNOret4xKxXjCYJgg0DcyersUwpW3qdZGwbncP8S9XDGGzrMP5FPqlaH5rCacqw0TbqwZusnz4nbAL1axZdPDavJ4EOhECza6TRMdcY9wRqg9U+BDp8bs0/gOJI6XqWxoZMQYdTxmJJb9uPNI4KPLp+iKwkgg9U/4wKEKCCcsAprQ2GGt5w2TIZFoxgDvnEy4MfY6ZZs8X18oQOWThMHTAAv/ERt8rxTHOPMliO+wIjJ+zkUJ3bVSJ2+6P2I1N2qpSuWcSbkHihVNh+WEV4SYsPqcah4HeUBPXAav399vUw=

notifications:
  email:
    on_success: never
