[package]
name = "strife"
version = "0.1.0"
authors = ["James Whaley <juicy66173@gmail.com>"]
description = "A lightweight library for the Discord API."

homepage = "https://github.com/Juici/strife"
repository = "https://github.com/Juici/strife.git"
documentation = "https://docs.rs/strife"
readme = "README.md"
license = "MIT"

keywords = ["discord", "api"]
categories = []

edition = "2018"

[dependencies]
