[package]
name = "strife"
version = "0.0.1"
authors = ["James Whaley <juicy66173@gmail.com>"]
description = "A lightweight library for the Discord API."
license = "MIT"
readme = "README.md"

documentation = "https://docs.rs/strife"
homepage = "https://github.com/Juici/strife"
repository = "https://github.com/Juici/strife"

categories = ["api-bindings", "asynchronous"]
keywords = ["discord", "api", "async"]

edition = "2018"

[dependencies]
bitflags = "1.2"
chrono = "0.4"
int-enum = "0.1"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
